/**
 * Assemble demo/paph4x.html — the PAPH evidence bench.
 *
 * The bench is a SINGLE file you can hand to anyone: no server, no network,
 * fonts included.  That property is worth keeping, but a hand-inlined engine
 * goes stale the moment the comparator moves, so the file is generated instead
 * of edited: this script inlines the CURRENT engines into the page —
 *
 *   src/wire.cjs, src/paph-js.cjs, demo/cal-core.cjs   the JavaScript engine
 *   wasm/paph.js                                         the WebAssembly glue,
 *                                                        as a classic script
 *   wasm/paph.wasm                                       gzip + base64
 *
 * Run `npm run build:bench` after any engine change (and `npm run build:wasm`
 * after any Rust change) and the bench cannot silently disagree with the
 * package.  Sources live in demo/bench4x/ — brand CSS (the Pixagram design
 * system), the page body, and the bench application.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { gzipSync } from 'node:zlib';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const src = join(root, 'demo', 'bench4x');
const read = (...p) => readFileSync(join(...p), 'utf8');

const brandCss = read(src, 'brand.css');       // @font-face payloads + design tokens
const appCss = read(src, 'bench.css');         // application layer, borderless system
const body = read(src, 'body.html');           // the nine sections
const app = read(src, 'bench.js');             // the bench application

const engines = [
  ['wire — the PAPH fingerprint (SPEC-003); 4.2 raised the tier-2 budget to 512, not the format', read(root, 'src', 'wire.cjs')],
  ['paph-js — comparator 42 (SPEC-004.2) on the entry, 41 frozen beside it', read(root, 'src', 'paph-js.cjs')],
  ['cal-core — the calibration loop the bench shares with the suites', read(root, 'demo', 'cal-core.cjs')]
];

/* The glue is an ES module; a page that has to work from file:// gets it as
   a classic script.  Every edit is asserted, so a change to the glue that this
   transform does not understand fails the build instead of the page. */
function classicGlue(esm) {
  let s = esm;
  const edits = [
    [/^export async function init\(/m, 'async function init('],
    [/^export function simdSupported\(/m, 'function simdSupported('],
    [/^export class Side /m, 'class Side '],
    [/^export class Profile /m, 'class Profile '],
    [/^export class XProfile /m, 'class XProfile '],
    [/^export class XSide /m, 'class XSide '],
    [/^export class Engine /m, 'class Engine '],
    [/^export \{ DEFAULTS, STATES, EXECUTIONS, RANK_FIELDS, XRANK_FIELDS, XSCREEN_FIELDS, ABI, X_ABI, WIRE_VERSION, KEYS_VERSION \};\n/m, ''],
    [/^export const backend = 'wasm';\n/m, '']
  ];
  for (const [re, to] of edits) {
    if (!re.test(s)) throw new Error('build-paph4x: the glue no longer matches ' + re);
    s = s.replace(re, to);
  }
  s = s.split('import.meta.url').join("(typeof location !== 'undefined' ? location.href : 'file:///')");
  if (/^export /m.test(s) || s.includes('import.meta')) throw new Error('build-paph4x: unconverted ESM left in the glue');
  return '(function () {\n\'use strict\';\n' + s +
    '\nwindow.paphWasm = { init: init, simdSupported: simdSupported, Engine: Engine, Side: Side,\n' +
    '                    Profile: Profile, XProfile: XProfile, XSide: XSide, STATES: STATES,\n' +
    '                    EXECUTIONS: EXECUTIONS, DEFAULTS: DEFAULTS };\n})();';
}

const wasmFile = join(root, 'wasm', 'paph.wasm');
let wasmScript = '/* no WebAssembly build — run npm run build:wasm */';
let wasmNote = 'without WebAssembly';
if (existsSync(wasmFile)) {
  const raw = readFileSync(wasmFile);
  const gz = gzipSync(raw, { level: 9 });
  wasmScript = classicGlue(read(root, 'wasm', 'paph.js')) + '\n' +
    'window.PAPH_WASM = { gzip: true, bytes: ' + raw.length + ', data: "' + gz.toString('base64') + '" };';
  wasmNote = `WebAssembly ${(raw.length / 1024).toFixed(0)} kB (${(gz.length / 1024).toFixed(0)} kB gzipped)`;
}

const out = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PAPH 4.2 — Evidence Bench</title>
<!-- Generated by tools/build-paph4x.mjs — edit demo/bench4x/*, not this file. -->
${brandCss}
${appCss}
</head>
${body}
${engines.map(([label, code]) => `<script>/* ${label} */\n${code}\n</script>`).join('\n')}
<script>/* paph — the Rust reference as WebAssembly: glue (wasm/paph.js, as a classic script) and the module */
${wasmScript}
</script>
<script>${app}</script>
</body>
</html>
`;

const dest = join(root, 'demo', 'paph4x.html');
writeFileSync(dest, out);
console.log(`demo/paph4x.html — ${(out.length / 1024).toFixed(0)} kB, engines inlined from src/ and wasm/ (${wasmNote})`);
